# Generated by Django 5.2.14 on 2026-05-14 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_key", models.CharField(max_length=64, unique=True)),
                ("hostname", models.CharField(default="", max_length=255)),
                ("platform", models.CharField(default="", max_length=128)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "vendor_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "vendor_contact",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("scan_interval", models.IntegerField(default=3600)),
                ("scan_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "clients",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("value", models.TextField(blank=True)),
            ],
            options={
                "db_table": "settings",
            },
        ),
        migrations.CreateModel(
            name="AddonDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("category", models.CharField(blank=True, default="", max_length=128)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="scanner_api.client",
                    ),
                ),
            ],
            options={
                "db_table": "addon_devices",
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_type", models.CharField(default="scheduled", max_length=32)),
                ("scan_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="scanner_api.client",
                    ),
                ),
            ],
            options={
                "db_table": "scan_results",
                "ordering": ["-created_at"],
            },
        ),
    ]
