# Generated by Django 5.2.7 on 2026-05-14 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanresult",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scans",
                to="scanner_api.client",
            ),
        ),
    ]
